### ISSUE TITLE
Joomla 5 template in v2-varnish is same as v2-http3

### ISSUE THREAD

**Issue by ccMatrix** [cloudpanel-io/vhost-templates#33]
There seems to be a copy/paste error with the vhost template for Joomla 5. The file in https://github.com/cloudpanel-io/vhost-templates/blob/master/v2-varnish/Joomla/Joomla%205 is the same as the v2-http3 leading to problems with the template in CloudPanel on Ubuntu 22.04 and the old nginx version since it doesn't know the new directives.

**Comment by cloudpanel-io** [comment]
Thanks @ccMatrix 
It has been fixed; tomorrow morning, everyone will get the fix automatically.

**Comment by ccMatrix** [comment]
Checked with `sudo -u clp bash -c "clpctl vhost-templates:import"` and verified. Thanks for the fix.
